create sequence author_seq
    start with 1
    increment by 50;

create sequence book_seq
    start with 1
    increment by 50;

create table author
(
    id         bigint not null,
    first_name varchar(100),
    last_name  varchar(100),
    primary key (id)
);

create table book
(
    id          bigint not null,
    description varchar(255),
    genre       varchar(20),
    rate        double,
    title       varchar(100),
    author_id   bigint not null,
    primary key (id)
);
create table user_role
(
    user_id bigint not null,
    roles   varchar(255)
);
create table users
(
    user_id   bigint generated by default as identity,
    password  varchar(255) not null,
    user_name varchar(255) not null,
    primary key (user_id)
);

alter table book
    add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author;
alter table users
    drop constraint if exists UK_k8d0f2n7n88w1a16yhua64onx;
alter table users
    add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table user_role
    add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;